import "../../style/Project.css";

export default function MagicTiles() {
    return (
        <div className="magic-tiles">
            <div className="magic-tiles-overview">
                <div className="video-demo">
                    <iframe
                        src="https://www.youtube.com/embed/j1o4nHv-O-M"
                        allowFullScreen
                    />
                </div>
                <div className="project-bio">
                    <div className="project-title">
                        <h1>Magic Tiles</h1>
                    </div>
                    <div className="project-context">
                        <p>2026 May, Computational Sound Final</p>
                        <p>
                            A real-time computer vision powered music maker. By tracking hand movement and 
                            gestures, different drum beats and synth notes can be placed and played on a virtual grid. The project
                            is built with Mediapipe, React, Web Audio API, and Three.js. 
                        </p>
                        <div className="project-technicals">
                            <h3>UI</h3>
                            <p>On top of a live camera feed, there's two layers: an invisible grid
                                that divides the screen into a grid, handling pixel coordinates, and a visible canvas
                                element rendered by Three.js that controls all visual components, such as a placed dot and 
                                3D animation.
                            </p>
                            <h3>Computer Vision</h3>
                            <p>Using Mediapipe's 21 landmarks per hand detection, we were able to
                                track user's hands, where the right hand acts like a cursor controlling 
                                the coordinates and the left hand classifies gestures and triggers certain events 
                                based on said gestures.
                            </p>
                            <h3>Audio</h3>
                            <p>The full audio pipeline is built on Tone.js, a WebAudio API Wrapper. Sound is loaded
                                into containers that can be retrieved based on certain events. For the synth sounds specifically, 
                                the sound is generated by a polyphonic synthesizer based on mathematically accurate oscillations and 
                                amplitudes. 
                            </p>
                        </div>
                    </div>
                    <div className="project-github">
                        <a href="https://github.com/maoo1/magic-tiles" target="_blank" rel="noopener noreferrer">
                            View on Github!
                        </a>
                    </div>
                </div>
            </div>
            <div className="project-tryout">
                <h2>Try it out!</h2>
                <hr></hr>
                <iframe
                    src="https://maoo1.github.io/magic-tiles/"
                    allowFullScreen
                />
                <div className="magic-tiles-instructions">
                    <p> Right index finger controls the cursor; left hand pinky (change mode), left hand index finger up (place note)</p>
                </div>
            </div>
        </div>
    )
}